### ISSUE TITLE
Add icons inside 'vs-circles' on vs-slider

### ISSUE THREAD

**Issue by thepepperone** [lusaxweb/vuesax#248]
**Is your feature request related to a problem? Please describe.**
Would love to see icons inside the vs-circle on vs-slider component

**Describe the solution you'd like**
A '+' and '-' icons could be start as default indicating a max or min values

**Additional context**
An example: 

![image](https://user-images.githubusercontent.com/43367090/45669660-4ccd4200-bb53-11e8-9f42-855d5fc3f503.png)

**Comment by luisDanielRoviraContreras** [comment]
It would be great, and it looks great

the only thing is that it is something complex because although one is more visually can be both, what I mean is that the `-` could be visually after the` + `and thus confuse

but you can make a property as `signs` and program that functionality so that the one with the least value visually always has the sign` -` and thus with the `+` sign

if you want to make a PR notify me to assign it and if you do not tell me to take it into account for future updates

Thank you

**Comment by luisDanielRoviraContreras** [comment]
This functionality can not be achieved because the component does not really have a maximum or minimum in itself, it can be visually the largest to convert into a smaller one, thanks for the contribution
