### ISSUE TITLE
Feature Request: Layout

### ISSUE THREAD

**Issue by robisemicolon** [lusaxweb/vuesax#3]
Where is the layout? This is amazing, but ....

**Comment by lusaxweb** [comment]
when you mean, where is the design? which is specific and thank you very much for the contribution greetings

**Comment by robisemicolon** [comment]
I mean, layout like container, grid, etc.

**Comment by lusaxweb** [comment]
Well, I'm already working on that as soon as I finish, I would like to thank you very much for the contribution

**Comment by atilkan** [comment]
Css-Grid is layout.

**Comment by areyouse7en** [comment]
awesome works. I'll keep watching~

**Comment by mornir** [comment]
Hi! I've just learn about Vuesax today and I really like the design of the components. I've been looking for a lightweight component library (without layout, color theme, typography, etc.) and Vuesax seem to be exactly what I need.

I agree with @atilkan. Now that CSS Grid is out (and combined with Flexbox), is it really necessary to build a custom grid system? In my opinion, web developers should start learning CSS Grid instead of spending time learning a new grid system for every CSS framework out there. Believe me, CSS Grid is really powerful 🌟

Adding such a feature would only make sense if Vuesax is committed to supporting Internet Explorer. Is that the case? Because the website hosting the docs does not work well on IE11...

Just my two cents.

**Comment by atilkan** [comment]
@mornir css-grid is supported on ie11. Many people dont know that css-grid came from microsoft.

**Comment by mornir** [comment]
I was referring to the latest implementation. IE11 supports an older version. But it's true that it first came from Microsoft:astonished:
https://caniuse.com/#feat=css-grid

**Comment by jasterba** [comment]
What about sass implementation?

**Comment by luisDanielRoviraContreras** [comment]
Good friends and add support to layout thank you very much to all the documentation here
https://lusaxweb.github.io/vuesax/#/en/docs/layout/grid
