### ISSUE TITLE
Feels slow

### ISSUE THREAD

**Issue by kirschkern** [lusaxweb/vuesax#30]
I like the fresh ideas and look of vuesax. However there is one thing that keeps me away from using it. It all feels very slow. Especially when clicking anything there seems to be a short delay before the element reacts. And often the delay feels different each time I click. I expect instant visual feedback from my app.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much, we would love you to say what are the components that have that delay to review the animations if they have them and their weight in itself

**Comment by kirschkern** [comment]
I see it in most components using Firefox 59.0.2 (with a lot of tabs open). Eg. the hover effect on the buttons. And it's not consistent so it seems that it depends on the browser doing some garbage collection or whatever.
I get a smoother result using Chrome and even Edge.

**Comment by luisDanielRoviraContreras** [comment]
thank you very much I will review the problem to solve it I warn you to review it

**Comment by e200** [comment]
At least all components have a delay, but it seems like its happening only when there's a lot of VueSax components being used.

I think the delay its because there's a lot of animations running and probably some of the components use animations that have a lot of calculations or run in more then 60 FPS.

**Comment by e200** [comment]
Really awesome project bro!

**Comment by baumannzone** [comment]
I feel it too, it looks like it's slow. Anyway, it's a good job!

**Comment by fergardi** [comment]
I was at first shocked by the detail of this framework. However, and since I'm using it for a Cordova port on mobile devices, this slowish feeling has stopped me from using it.

In my desktop computer it feels smooth, but in my laptop feels a bit slow. In mobile it lags a lot.

I'm really looking forward to it being more "responsive" and "touch friendly" with low RAM an processor capabilities, because I really (REALLY REALLY) like how this looks and feels.

Maybe if you reduce the quantity (or quality) of the animations/transitions, it could be smoother.

**Comment by luisDanielRoviraContreras** [comment]
Well, I'm working on it, the idea is to make the framework a lot faster and with fewer animations, of course it's very extensive and it takes time

and with regard to the devices it seems to me that you have to remove almost all the animations and leave only some so that you feel nice but compatible

**Comment by fergardi** [comment]
Thanks for the answer!

Here is some documentation that could be interesting to read: https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108

I'm looking forward this project with much enthusiasm. Maybe I could help you creating some new componentes. I could start by the easy ones, tags and cards for example, which require close to none transitions to work.

**Comment by luisDanielRoviraContreras** [comment]
Well I would love clear without any problem, the component you want to help doing first take it on the same issues to not re-work on them

**Comment by fergardi** [comment]
The new VuePress documentation pages feels so much faster and smoother now!

**Comment by luisDanielRoviraContreras** [comment]
Almost all the components were improved with respect to speed of animation and performance any problem please add an issues only of the specific component to improve it or accommodate it thanks to all for the contribution
