### ISSUE TITLE
vs-dialog mounting element + other components

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#453]
hi, far now everything is working fine somehow.
But I got problem with how vuesax creates vs-dialog component outside of the `div#app`.

I have dark layout in my project which can be triggered using switch component. And it applys `theme-dark` class to my layout div. which is right after `div#app`.

So problem is becuase `vs-dialog` is created outside of `div#app`. I can not figure out if it's dark layout or light layout.

So, I can not style `vs-dialog` component.

This goes same for all elements which are created outside of `div#app`.
which includes:

1. Dialog
2. Popup
3. Dropdown
4. Select

I think changing `document.body` is really bad idea. After reading this article.
[Article](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375)
There must be another way!

**Comment by AngelAngelov** [comment]
I think it is a good idea to choose the parent element for the components that are rendered before document.body.firstChild by default. In the SideBar where you have parent property which is great. 

But I have big issue with components like popup that are inserted before document.body.firstChild. 
I am making SPA application. When the popup is shown and you hit back button on the browser the router navigates to another page but the popup stays but not working, because it is outside the <router-view/> tag and it is not destroyed on router navigation.

Is there any chance to fix that please?

**Comment by luisDanielRoviraContreras** [comment]
@AngelAngelov a new parent property was added which as a value is an html node where the component is going to be added
