### ISSUE TITLE
dropdown component closes if I add input just like in demo page

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#456]
**Is your feature request related to a problem? Please describe.**
Hi, I am having search input in my vs-dropdown component. User opens dropdown and when he clicks on search input dropdown gets closed due to it's normal behaviour of _close if, click is outside of dropdown_

**Describe the solution you'd like**
Dropdown should not close if I click inside of dropdown.

**Additional context**
You can check dropdown component page and try to add some text in input field. As you try to enter something dropdown closes.

**Comment by jsinhSolanki** [comment]
I think this is happening since this [pull request](https://github.com/lusaxweb/vuesax/pull/403).
Hey, @guastallaigor can you please help me in this one?

**Comment by guastallaigor** [comment]
Hello @jsinhSolanki. The code right now is rather different, but I'm looking into it and I couldn't find the problem.
Isn't a search input inside a dropdown component the same as [select autocomplete](https://lusaxweb.github.io/vuesax/components/selects.html#autocomplete)?
Because by default, the dropdown can't do searches inside the dropdown, you would had to code that yourself and the behavior I guess is going to be unexpected.
Could you post share a codepen or some sandbox link to demonstrate the bug?
Thank you.

**Comment by jsinhSolanki** [comment]
Yes, every dropdown closes if we click on dropdown area.
I am using `vs-input` component in dropdown.

As per my knowledge dropdown can not handle inputs and similar stuffs becuase of it's closing behaviour.
But, what I was looking for was, is in this [jsfiddle](https://github.com/lusaxweb/vuesax/issues/456)
This can be achieved if we use previous version which only closes dropdown if we click on that item again.
For this purpose I removed dropdown component and added custom `div` for search input and placed `vs-input` inside so I can control that custom `div` however I want.

Finally, this is really very different from dropdown's normal behaviour so I am closing this.
By the way thanks for your contribution in dropdown. That was really helpful.
