### ISSUE TITLE
Some components are not working with latest vue release

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#462]
Hi, I would like to inform you that some of the components in vuesax is not working since I updated my vue to latest release.
e.g. Switch, checkbox etc.

You can check this with this [jsfiddle](https://jsfiddle.net/jsinh0001/zm15xnh4/)

**Comment by 201Factory** [comment]
:+1:

**Comment by azliabdullah** [comment]
ah no wonder. as a first time user, i was wondering what have i done wrong. my version is 3.8.24..
anybody has any workaround other than downgrading version?

**Comment by ishigami** [comment]
I was facing this same issue with vue 2.6.8. And to resolve this until the fix by the Vuesax team, I've changed my vue version to 2.5.22. And now run smoothly.

Just change the following lines in package.json
```
    "vue": "2.5.22",
    "vue-template-compiler": "2.5.22",
    "vue-server-renderer": "2.5.22", // if you are using nuxt
```

**Comment by azliabdullah** [comment]
@ishigami thank you so much! it does work. even though i prefer not to downgrade my vue version, but  i appreciate that. it seems many components aren't working with new vue version. anyone has experience this kind of issue with other framework such as vuetify, bootstrap-vue?

**Comment by WimpyMistake** [comment]
@azliabdullah i have used vuetify, bootsrap-vue, beaufy. was using vuesax in a POC project..but recently we decided to drop it from our project..the reason is this project is not maintained anymore....it gained popularity and has huge potential..it has quite a lot of contributors but the PRs are not even attended..there are critical issues not even assigned or attended (like this issue)..last few releases just consist of few lines of codes..
that's just my opinion if you considering to use this framework in a production or real project..this framework is in beta anyway..off course vuetify is not as beautiful as vuesax, but it's active and safer

**Comment by luisDanielRoviraContreras** [comment]
@jsinhSolanki @201Factory @azliabdullah @ishigami @WimpyMistake the components were fixed, and they work with the latest version of vue please if there are other components that present a problem to notify me to fix it

thank you very much everyone for the contribution and we are already active again, regards

**Comment by YkkJeff** [comment]
@luisDanielRoviraContreras unfortunately v3.8.59 has vs-switch, vs-checkboxes and vs-select not working on Safari.
vs-switch was working in 3.8.12 but that was not the case for vs-select for example :/

Those components were working in previous versions.

**Comment by TanzilIslam** [comment]
Hello,
In the version of "vuesax": "^4.0.1-alpha.23", the component **<vs-popup></vs-popup>** is not working.Please have a look on this.
