### ISSUE TITLE
Code language standard

### ISSUE THREAD

**Issue by pearofducks** [lusaxweb/vuesax#48]
There's a mix of English and Spanish in code.

For those who would contribute in the future with bugs/improvements, knowing or translating Spanish names creates an extra hurdle. Likewise for users who want to understand a component's implementation.

**Comment by luisDanielRoviraContreras** [comment]
Well really I am from Venezuela and it costs me a lot of English but I am improving that part so that I have more support Vuesax and that is understood much better

If you want you can help us with that part and translate what is in Spanish including the minimum would be very helpful thanks for the contribution

**Comment by luisDanielRoviraContreras** [comment]
All the components have the same language and it is much better understood thanks to the contribution
