### ISSUE TITLE
Fiddlejs from documentation doesn't work

### ISSUE THREAD

**Issue by Cuacha07** [lusaxweb/vuesax#533]
<!DOCTYPE html>
    <html>
    <head>
      <link href="https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.css" rel="stylesheet">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    </head>
    <body>
      <div id="app">
        <vs-button vs-type="filled">Hello World</vs-button>
        <vs-input placeholder="Placeholder" v-model="value1"/>
        <vs-input placeholder="Placeholder 2" v-model="value2"/>
        <vs-input placeholder="Placeholder 3" v-model="value3"/>
      </div>

      <script src="https://unpkg.com/vue/dist/vue.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.umd.js"></script>
      <script>
        new Vue({
          el: '#app',
          data: {
          	value1: '23423',
            value2: 'asdasd',
            value3: 'asdasdadsasd'
          }
        })
      </script>
    </body>
    </html>

Tried the fiddlejs example from "Getting Started" Section from the documentation and it doesn't work. Is there something wrong? I only get 1 input and i want 3 inputs.

**Comment by Jacrys** [comment]
@Cuacha07  This behaviour happens because you have set the vs-input as an empty element, e.g. ```<vs-input />```.  These are not empty elements and must be fully declared such as ```<vs-input placeholder="Placeholder"></vs-input>```. So the correct implementation would be:

```html
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>
  <div id="app">
    <vs-button vs-type="filled">Hello World</vs-button>
    <vs-input placeholder="Placeholder" v-model="value1"></vs-input>
    <vs-input placeholder="Placeholder 2" v-model="value2"></vs-input>
    <vs-input placeholder="Placeholder 3" v-model="value3"></vs-input> 
  </div>

  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.umd.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: {
      	value1: '23423',
        value2: 'asdasd',
        value3: 'asdasdadsasd'
      }
    })
  </script>
</body>
</html>
```

Basically, the vue engine doesn't see that you have closed that first input tag and tries to assume that everything up to the close div tag is irrelevant.  It might help to look at the input section in the [documentation](https://lusaxweb.github.io/vuesax/components/input.html#label-placeholder). If you click the `</>` button, it will provide the code.
