### ISSUE TITLE
[3.10.0] Style issue with vx-card and other vx-* classes

### ISSUE THREAD

**Issue by lk77** [lusaxweb/vuesax#666]
- Your OS : Ubuntu 18.04
- Node.js version : 10.11.0
- Vuesax version : 3.10.0
- Browser version : chrome 76
- Which package manager did you use for the install? npm

Hello,

we have an issue with vx-card, and other vx-* classes
they are now hidden by this style in vuesax.styl  :
```
*[class*="vx-"]
  display: none !important
  pointer-events: none !important
  opacity 0 !important
  visibility hidden !important
```
What is the purpose of this style ?

there is also this code :
```
window.addEventListener('scroll', () => {
    document.querySelectorAll('*[class*="vx-"]').forEach((item) => {
      item.parentElement.removeChild(item)
    })
  })
```
that breaks everything

this was added in : https://github.com/lusaxweb/vuesax/commit/c1641aec7a8138272eb27333150cc69c08ecafcb

thanks.

**Comment by tiagosimoesdev** [comment]
Unfortonely vuesax theme from themeforest isn't official so this vuesax official won't support it.

**Comment by WilliamBlais** [comment]
It seems like it was deliberately added. Why?

**Comment by tiagosimoesdev** [comment]
Themeforest vuesax won't support the real creator of the framework and is using vuesax name as official.

**Comment by lk77** [comment]
So you are telling me that you are taking aggressive actions against your users ?

We are not responsible of this.

We have fixed this, overrided the style and removed the listener, you just lost our trusts.

Your components are full of bugs, start by fixing those and don't mess around with other people work.. 

We have been forced to remove 90% of vuesax components from our app because they are not tested well enough.

**Comment by tiagosimoesdev** [comment]
I agree . I'm in the same boat . I bought the theme from themeforest thinking it was oficial,  apparently it's not  . Spent 3 months developing a app with vuesax . While I can understand the vuesax author , for other people taking credit for his work . I think the people from themeforest should support the author and change the name and everything will work out . 

I can't maintain my project , with vuesax framework constantly trying to sabotage it just because I bought the theme . 

We should have a discussion on what's the best solution for all should be.

**Comment by decowboy** [comment]
> We have fixed this, overrided the style and removed the listener, you just lost our trust.
> 
> Your components are full of bugs, start by fixing those and don't mess around with other people work..

Let's not forget that this is a free and open-source project.
I don't disagree with your complaints, but we should appreciate the kind efforts nonetheless.

@tiagosimoesdev 
Pretty shocked to hear about the disagreement with Pixinvent, who published the template on Themeforest.
Is there any place that mentions some more information?

**Comment by tiagosimoesdev** [comment]
@luisDanielRoviraContreras  told me in discord . He even tried to communicate with pixinvent and they were rude with him , from what he told in discord . I sure hope Pixinvent get the idea that their project won't go far without @luisDanielRoviraContreras  approval.

**Comment by luisDanielRoviraContreras** [comment]
Good to all, I am the creator of vuesax and I want to clarify things for my whole community, I really want to do something bad against you but I really speak best with the creators of that topic to find a solution but they literally laughed at me and treated me as if my work is worth nothing by joking and insulting me, after that I decided with my brother that we do not want people like that to use our work and less when they steal our name blatantly and do not even they have helped in any aspect

In the end we really agree that if they change their name, we will eliminate that code and make the passes. We are waiting for them to at least change the name and tell us but they really don't care and keep making money, so I don't think they will.

I apologize to everyone who bought the item and now they are involved in this problem

**Comment by WilliamBlais** [comment]
@luisDanielRoviraContreras Hey buddy, you do an amazing work with vuesax, it's a shame that the themeforest guys use the name without authorisation and support. Why not do something like a message in the console denouncing the situation? This way, people would actually realise that the theme forest guys stole the name instead of "oh, this vuesax version isn't working".

**Comment by lk77** [comment]
> > We have fixed this, overrided the style and removed the listener, you just lost our trust.
> > Your components are full of bugs, start by fixing those and don't mess around with other people work..
> 
> Let's not forget that this is a free and open-source project.
> I don't disagree with your complaints, but we should appreciate the kind efforts nonetheless.
> 
> @tiagosimoesdev
> Pretty shocked to hear about the disagreement with Pixinvent, who published the template on Themeforest.
> Is there any place that mentions some more information?

i know it's a free and open source project, and i appreciate the work. 
But this kind of behaviour is not open minded, it's a 'proprietary software' behaviour, like microsoft could do.

**Comment by decowboy** [comment]
My biggest concern is that I don't know how to remedy the situation.
It's going to be really difficult to change my code to not use any vx-components, as all the styling and scripts are largely tied to them.
What do I do now?

Remain on 3.9.x forever?
Start over?
Keep removing any vx-protection manually?

Those aren't great options.

**Comment by lk77** [comment]
ii've choosed the last option :
```
window.addEventListener('scroll', function (event) {
    event.stopPropagation();
}, true);
```
```
*[class*="vx-"] {
	display: block !important;
	pointer-events: unset !important;
	opacity: 1 !important;
	visibility: unset !important;
}
```
it's not working so well, but it's ok for now.

**Comment by jsinhSolanki** [comment]
Hello @lk77 @decowboy @WilliamBlais @tiagosimoesdev @luisDanielRoviraContreras ,
Our team talked on this as Luis stated. We are on the verge of releasing a big update with new features and **big changes like API ready + Name change**.
This will surely resolve name conflicts. Plus we are also going to update our docs' theme so it doesn't look like Vuesax Framework's.

Regarding the name, we used as `Vuesax` because we are using this framework. We thought if we get success on this, both framework and we will benefit. However, people are getting misunderstood between the creator of the theme and creator of framework. So, Luis and we decided to change our theme's name in our next big release.

We aren't taking any credit of this framework. We also mentioned framework links and reference in our theme's docs and you can also check framework reference on our ThemeForest item page.

We are trying our best to resolve name conflict and all should see the same in our next release.

**Comment by decowboy** [comment]
@decowboy @luisDanielRoviraContreras 
I do hope you won't require your users to go through extensive renaming or migration in order to keep everything working.
Since many styling and scripts are tied to vx-classes that would be very time-consuming.

**Comment by decowboy** [comment]
@jsinhSolanki @luisDanielRoviraContreras 
I do hope you won't require your users to go through extensive renaming or migration in order to keep everything working.
Since many styling and scripts are tied to vx-classes that would be very time-consuming.

**Comment by tiagosimoesdev** [comment]
Since there is an agreement with vuesax and the theme , is it possible to remove 

`
*[class*="vx-"]
  display: none !important
  pointer-events: none !important
  opacity 0 !important
  visibility hidden !important
`

and 

`window.addEventListener('scroll', () => {
    document.querySelectorAll('*[class*="vx-"]').forEach((item) => {
      item.parentElement.removeChild(item)
    })
  })`

**Comment by jsinhSolanki** [comment]
Hi @tiagosimoesdev @decowboy @lk77 @WilliamBlais @luisDanielRoviraContreras 
We updated our template name in our latest major release(v4.0). Please check it [here](https://themeforest.net/item/vuexy-vuejs-html-laravel-admin-dashboard-template/23328599).

Now onwards everything will be normal and you can use latest update of Vuesax Framework once @luisDanielRoviraContreras updates code.

~ Regards

**Comment by tiagosimoesdev** [comment]
I'm glad that both parties came to an agreement . Hope that Luis will be more motivated to update v3

**Comment by lk77** [comment]
@jsinhSolanki thanks !!
