### ISSUE TITLE
Cannot read property 'catch' of undefine

### ISSUE THREAD

**Issue by kevinzie** [lusaxweb/vuesax#851]
- OS: Windows 10
- Node Version : v12.18.1
- Vuesax : V3.11.17
- Browser : Version 83.0.4103.106 (Official Build) (64-bit)
- Package : (@nuxtJS, moment.js )

Error appear when I use `:to` in vs-button

```
<vs-button type="border"
color="#5cac00" :to="{name: 'user-invoice-invoice_id', params: {invoice_id: trx.invoice_id }}">
view  invoice
</vs-button>
```

![Screenshot_171](https://user-images.githubusercontent.com/7718704/85886933-1c7b0300-b811-11ea-9ab0-b6ab8c3cadaa.png)

**Comment by thespino** [comment]
Same error. I solved by removing the call to `catch` function after `this.$router.push(this.to)` in this file:
[https://github.com/lusaxweb/vuesax/blob/bb45a39f547636ca65b2046811023df417abaeff/src/components/vsButton/vsButton.vue#L224](https://github.com/lusaxweb/vuesax/blob/bb45a39f547636ca65b2046811023df417abaeff/src/components/vsButton/vsButton.vue#L224)

So it should look like:
`this.$router.push(this.to)`

Then rebuild with `npm run build` and it should work.
Anyway, this is not a real solution because it doesn't fire the `routeErr` event, so maybe you can wrap in a try-catch, but not sure it would handle the error. Note that I'm using nuxtjs too, so maybe it depends on it, not sure, but in my case is fine.

Hope it helped

**Comment by kevinzie** [comment]
Thank you @thespino ... it works!

**Comment by cedvan** [comment]
Hi, 

Edit `vuesax/src/components/vsButton/vsButton.vue` is a very bad solution, this file is in node-modules directory....

I'm using NuxtJS too, this error is strange. Vuesax must have $router in context..

**Comment by cedvan** [comment]
Maybe router version from NuxtJS is too old ?

**Comment by kevinzie** [comment]
> Hi,
> 
> Edit `vuesax/src/components/vsButton/vsButton.vue` is a very bad solution, this file is in node-modules directory....
> 
> I'm using NuxtJS too, this error is strange. Vuesax must have $router in context..

of course not. I didn't change anything in the vuesax file. I make changes by extending VsButton Component.



```
const Base = Vue.options.components["VsButton"];
const VsButton = Base.extend({
    props: {
        to:{
            default:false,
            type:String | Object
        },
    },
    methods: {
        routerPush() {
            this.$router.push(this.to)
        },
    }
});

Vue.component('VsButton', VsButton);
```
