### ISSUE TITLE
Suggestion about components and my thank you

### ISSUE THREAD

**Issue by DeehSlash** [lusaxweb/vuesax#92]
First, I want to thank the developer of this project for trying to do this. 
It's been a while since I'm looking for frameworks with a different design. In a world where most frameworks look like Bootstrap or they are Material Design based, this framework seems like a hope to me.

I mean, I don't hate Material Design, I used it a lot, but I'm getting sick of so much Material Design. Bootstrap and other related frameworks, they are so basic in design and every site uses them, I just can't use them. I always liked Semantic UI, but the dependency on jQuery and the lack of updates are what keeps me from using it again.

And then there is Vuesax, integrated with Vue which I love, and with a much different design proposal. So thanks to who are working on this project.

But, on the other side... There's so much to do yet. This is my first time using this framework, but I'm only using it in a small project. I still can't use it in a bigger project because there are so many components that I'm missing, like a navigation drawer, helpers, etc. I know this is a new framework and it's still evolving, but I really expect to see new things. I would suggest taking a look at Vuetify, which is Material Design based, but it's so complete that I can use it in any project, big or small. So I would be very happy to see Vuesax reaching a similar level, so I can use it anywhere.

So, keep it up! It's getting good!
And those gradient buttons are perfect (it's what made me love Vuesax haha).

Thanks.

**Comment by luisDanielRoviraContreras** [comment]
thank you very much I share everything you say and that's why I love vuesax I love design and innovate not always the same and that way I want to arrive, thanks for using Vuesax and we will really continue to improve them and making new components to reach the level of being able to use it in a real application and without needing another framework

good many of the components have a nice design by my brother's designer and helps me doing illustrations, logo and improve the components visually so I think vuesax has much potential [dribbble](https://dribbble.com/ManuelRovira)

vuesax as you say is new and is in process and hope to get to the level of the great frames having all the components stable and design we characterized and difference and again thank you very much for use vuesax this is the aim improve the community and help create and do great things
